phenoscape/phenoscape-kb-services

- apiary.apib
> Makes example study IRI and NeXML study IRI consistent.

- src/main/scala/org/phenoscape/kb/JSONResultItem.scala
- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Term.scala
> Restore TSV output for taxon list output

- src/main/scala/org/phenoscape/kb/Similarity.scala
Somehow this was not staged in previous merge.
> Add missing import.

- swagger/swagger.yaml
> Document subsumer matrix service.

- src/main/scala/org/phenoscape/kb/Main.scala
> Support POST for OntoTrace.

- swagger/swagger.yaml
> Generated code by SwaggerHub

- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Study.scala
> Return matrix for study as application/xml.

- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Term.scala
> Generalize term search.

- src/main/scala/org/phenoscape/kb/AnatomicalEntity.scala
> Add newline in results EOF

- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Term.scala
> Provide option to make use of part_of for ancestor and descendant queries.

- src/main/scala/org/phenoscape/kb/AnatomicalEntity.scala
- src/main/scala/org/phenoscape/kb/Main.scala
- src/test/scala/org/phenoscape/kb/MatrixRendererTest.scala
> Preserve user specified order of iris in dependency matrix

- src/main/scala/org/phenoscape/kb/CharacterDescription.scala
- src/main/scala/org/phenoscape/kb/Study.scala
- src/main/scala/org/phenoscape/kb/Taxon.scala
> Return character id and label in the results of the study/phenotype kb-service

- build.sbt
- src/test/scala/org/phenoscape/kb/MatrixRendererTest.scala
> Migrate matrix renderer test to utest

- src/main/scala/org/phenoscape/kb/Term.scala
Return correct number of results according to limit. Fixes #122.
> Order text search results consistently for different values of limit

- swagger/swagger.yaml
> Document acceptance of json array of IRIs for kb services

- src/main/scala/org/phenoscape/kb/CharacterDescription.scala
- src/main/scala/org/phenoscape/kb/PresenceAbsenceOfStructure.scala
- src/main/scala/org/phenoscape/kb/Taxon.scala
- src/main/scala/org/phenoscape/kb/queries/DirectPhenotypesForTaxon.scala
@Shalsh23 I went ahead and fixed this one since I was already looking at it.
> Make character IRI and label available where needed.

- src/main/scala/org/phenoscape/kb/CharacterDescription.scala
> Combine character id and label into a single json object

- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Term.scala
- swagger/swagger.yaml
I haven't touched `computedLabel` method. Should I update/remove it?
> Issue 139 - merge term labels

- src/main/scala/org/phenoscape/kb/CharacterDescription.scala
- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Phenotype.scala
> Implement phenotype info service.

- src/main/scala/org/phenoscape/kb/Similarity.scala
> Add implementation for similarity/frequency for genes corpus

- src/main/scala/org/phenoscape/kb/Term.scala
> Return null if label doesn't exist

- src/main/scala/org/phenoscape/kb/Main.scala
- swagger/swagger.yaml
There is a big diff for the route definition, because everything is indented one extra to the right.
> Convert None responses for Option values into 404.

- swagger/swagger.yaml
> Update results json in api docs

- src/main/scala/org/phenoscape/kb/KB.scala
- src/main/scala/org/phenoscape/kb/KBVocab.scala
- src/main/scala/org/phenoscape/kb/Main.scala
- swagger/swagger.yaml
> Issue 179 kb metadata

- src/main/scala/org/phenoscape/kb/Taxon.scala
- swagger/swagger.yaml
> Add synonym detail to taxon info

- build.sbt
- src/main/scala/org/phenoscape/kb/AnatomicalEntity.scala
- src/main/scala/org/phenoscape/kb/Graph.scala
- src/main/scala/org/phenoscape/kb/KB.scala
- src/main/scala/org/phenoscape/kb/Phenotype.scala
- src/main/scala/org/phenoscape/kb/Similarity.scala
- src/main/scala/org/phenoscape/kb/Taxon.scala
- src/main/scala/org/phenoscape/kb/TaxonPhenotypeAnnotation.scala
- src/main/scala/org/phenoscape/kb/Term.scala
- src/main/scala/org/phenoscape/kb/queries/DirectPhenotypesForTaxon.scala
- src/main/scala/org/phenoscape/kb/queries/GeneAffectingPhenotype.scala
- src/main/scala/org/phenoscape/kb/queries/StudiesRelevantToPhenotype.scala
- src/main/scala/org/phenoscape/kb/queries/TaxaWithPhenotype.scala
- src/main/scala/org/phenoscape/kb/queries/TaxonAnnotations.scala
- src/main/scala/org/phenoscape/kb/queries/TaxonPhenotypes.scala
- src/main/scala/org/phenoscape/kb/util/SPARQLEntityChecker.scala
- src/main/scala/org/phenoscape/kb/util/SPARQLInterpolatorOWLAPI.scala
Changed `sparql-interpolator` package to `sparql-utils` because of new expanded functionality. Moved OWL API extensions to a new `sparql-utils-owlapi` module.
> Update to new sparql-utils.

- src/main/scala/org/phenoscape/kb/KB.scala
Updates /kb/annotation_summary service.
Tested: 
1. Compared generated queries across old and new versions.
2. Compared results across old and new versions.
> Rewrite query using sparql interpolator

- src/main/scala/org/phenoscape/kb/Gene.scala
- src/main/scala/org/phenoscape/kb/KBVocab.scala
- src/main/scala/org/phenoscape/kb/queries/DirectPhenotypesForTaxon.scala
> Bug fix; rewrite query using sparql interpolator

- src/main/scala/org/phenoscape/kb/Graph.scala
- src/main/scala/org/phenoscape/kb/KBVocab.scala
- src/main/scala/org/phenoscape/kb/Main.scala
- swagger/swagger.yaml
Add parameter to furnish only directly related terms.
> Update term/property_neighbors/object service to use relation graph. 

- src/main/scala/org/phenoscape/kb/Term.scala
> Allow return of all search results using limit < 1.

- src/main/scala/org/phenoscape/kb/Term.scala
> WIP add classification to term info result.

- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Similarity.scala
- swagger/swagger.yaml
> Update similarity/profile_size service to work with relation graphs

- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Similarity.scala
- swagger/swagger.yaml
> Update frequency service to use term paths and handle relational terms

- src/main/resources/swaggerDocs/swagger.yaml
- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Similarity.scala
> Add similarity/profile service.

- src/main/resources/swaggerDocs/swagger.yaml
- src/main/scala/org/phenoscape/kb/Gene.scala
- src/main/scala/org/phenoscape/kb/Main.scala
- src/main/scala/org/phenoscape/kb/Similarity.scala
- src/main/scala/org/phenoscape/kb/Term.scala
> Add specifier pattern parameters for semantic similarity.

- src/main/scala/org/phenoscape/kb/Similarity.scala
> Improve performance of corpus size query.

- src/main/scala/org/phenoscape/kb/Term.scala
> Move FILTER to where it will not always fail.

- src/main/resources/application.conf.example
- src/main/scala/org/phenoscape/kb/App.scala
- src/main/scala/org/phenoscape/kb/Similarity.scala
> Use QLever endpoint for similarity frequencies query.

- src/main/resources/swaggerDocs/swagger.yaml
> Add genes corpus to API docs.
